env:
  browser: true
  es2021: true
  node: true
extends: standard
overrides: []
parserOptions:
  ecmaVersion: latest
rules: {
  semi: ["error", "never"],
  arrow-parens: ["error", "as-needed"],
  no-path-concat: ["error", "never"]
}
