language: node_js
node_js:
  - '14'

services:
  - mysql

# 設定參數(Travis CI 會按照參數分別執行)
env:
  - NODE_ENV=travis
    IMGUR_CLIENT_ID:${{secrets.IMGUR_CLIENT_ID}}
    JWT_SECRET:${{secrets.JWT_SECRET}}
    PORT:${{secrets.PORT}}

# 在 install 前執行的指令git p
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS ac_twitter_workspace_test default character set utf8mb4 collate utf8mb4_unicode_ci;'
  - npm install sequelize-cli -g

# 在執行測試之前的指令
before_script:
  - sequelize db:migrate
