# basic info
openapi: 3.0.0
info:
  title: "Simple Twitter API"
  description: "This is a sample server for Simple Twitter API.  You can find out more about this project at [our GitHub](https://github.com/ivyhungtw/twitter-api-2020) For this sample, you can use the api key `simple-twitter` to test the authorization filters."
  contact:
    name: "GitHub"
    url: "https://github.com/ivyhungtw/twitter-api-2020/"
  version: "1.0.0"
servers:
  - url: "http://localhost:3000"
  - url: "https://simple-twitter-api-2021.herokuapp.com"

# path tags
tags:
- name: "admin"
  description: "Admin related"
- name: "user"
  description: "User related"
- name: "tweets"
  description: "Tweets related"
- name: "followships"
  description: "Followships related"


# models
components:
  schemas:
    Users:
      type: "object"
      properties:
        id:
          type: "integer"
        name:
          type: "string"
        email:
          type: "string"
        password:
          type: "string"
        avatar:
          type: "string"
        role:
          type: "string"
          default: "user"
        introduction:
          type: "string"
        account:
          type: "string"
        cover:
          type: "string"
      xml:
        name: "Users"
    Tweets:
      type: "object"
      properties:
        id:
          type: "integer"
        UserId:
          type: "integer"
        description:
          type: "string"
      xml:
        name: "Category"
    Replies:
      type: "object"
      properties:
        id:
          type: "integer"
        userId:
          type: "integer"
        tweetId:
          type: "integer"
        comment:
          type: "string"
      xml:
        name: "Replies"
        
    Likes:
      type: "object"
      properties:
        id:
          type: "integer"
        userId:
          type: "integer"
        tweetId:
          type: "integer"
      xml:
        name: "Likes"
    Followships:
      type: "object"
      properties:
        id:
          type: "integer"
        followerId:
          type: "integer"
        followingId:
          type: "integer"
      xml:
        name: "Followships"