const express = require('express')
const passport = require('passport')
const { authenticated, authenticatedSuccess, authenticatedAdmin } = require('../middleware/auth')
const userController = require('../controllers/user-controller')
const adminController = require('../controllers/admin-controller')
const tweets = require('./modules/tweets')
const admin = require('./modules/admin')
const users = require('./modules/user')
const followship = require('./modules/followship')
const router = express.Router()

router.post('/admin/signin', passport.authenticate('local', { session: false }), adminController.signIn)
router.use('/admin', authenticated, authenticatedAdmin, admin)
router.use('/tweets', authenticated, tweets)
router.get('/auth/test-token', authenticated, authenticatedSuccess)
router.use('/users', users)
router.use('/followships', authenticated, followship)
router.post('/signin', passport.authenticate('local', { session: false }), userController.signIn)
module.exports = router
